version: '3'

services:
  app:
    build:
      context: stable_diffusion_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

#    depends_on:
#      - mongo
#    environment:
#      MONGO_URI: "mongodb://mongo:27017"

#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"